### ISSUE TITLE
1.19 crash on startup

### ISSUE THREAD

**Issue by SkarletShadows** [legosteenjaap/HorseInBoat#8]
Hello! I'm making a modpack and the modpack crashes when I add this mod! I'd love to use it D:

**CRASH LOGS RELEVANT TO THE MOD**

[06:18:09] [pool-3-thread-1/FATAL]: Mixin apply failed horseinboat.mixins.json:AbstractHorseMixin -> net.minecraft.world.entity.animal.horse.AbstractHorse: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException m_20191_()Lnet/minecraft/world/phys/AABB; in horseinboat.mixins.json:AbstractHorseMixin overrides a final method from net.minecraft.world.entity.Entity [MAIN Applicator Phase -> horseinboat.mixins.json:AbstractHorseMixin -> Apply Methods -> ()Lnet/minecraft/world/phys/AABB;:m_20191_ ->  -> Validate]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: m_20191_()Lnet/minecraft/world/phys/AABB; in horseinboat.mixins.json:AbstractHorseMixin overrides a final method from net.minecraft.world.entity.Entity [MAIN Applicator Phase -> horseinboat.mixins.json:AbstractHorseMixin -> Apply Methods -> ()Lnet/minecraft/world/phys/AABB;:m_20191_ ->  -> Validate]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.validateMethod(MixinTargetContext.java:521) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:446) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:532) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:518) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:386) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:177) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.<clinit>(MonsterRoomFeature.java:26) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at net.minecraft.world.level.levelgen.feature.Feature.<clinit>(Feature.java:81) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at net.minecraft.data.worldgen.features.AquaticFeatures.<clinit>(AquaticFeatures.java:20) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at net.minecraft.data.worldgen.features.FeatureUtils.m_236677_(FeatureUtils.java:24) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:665) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:139) ~[client-1.19-20220607.102129-srg.jar%23335!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by SkarletShadows** [comment]
The forge version was too high, I apologize!

**Comment by TLATER** [comment]
No pressure at all, but any chance for a 1.18 version that supports newer forge releases? Forge has long since moved on, and other mods in my pack require a more recent forge release.

I'd like to repeat, no pressure at all, thanks for the neat mod. Stuff like this should just be possible in vanilla already, silly sinking horses ;)

**Comment by legosteenjaap** [comment]
@TLATER I am sorry that i reacted so late. I tried the 1.18 version on the newest version of forge and it worked. Maybe you have stumbled upon a mod compatibility issue or something? Could you open a new issue and post something like a crash log there?

**Comment by TLATER** [comment]
> Maybe you have stumbled upon a mod compatibility issue or something? Could you open a new issue and post something like a crash log there?

Ack, my bad, I *thought* I'd tested the mod in isolation, but who knows, this tends to be a late night hobby. I'm on a bit of an extended holiday now, but I'll dig it back up when I'm back!
